### ISSUE TITLE
MYO Connect

### ISSUE THREAD

**Issue by GuiyinLi** [sebastiankmiec/PythonMyoLinux#1]
Do i need to install the "Myo Connect" in advance in linux

**Comment by sebastiankmiec** [comment]
You do not need to install Myo Connect in advance. In fact, I think the application you're referring to is only available on Windows.

**Comment by GuiyinLi** [comment]
Thanks.
It is normal to run the "gui_main.py" before.
But now there is an error, so I download the code. However, it is still the error:
```sh
(python3:27803): GLib-GObject-CRITICAL **: 16:09:02.155: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_object_ref: assertion 'object != NULL' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.155: gst_object_unref: assertion 'object != NULL' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.158: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.158: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.158: gst_bin_remove: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.158: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed
Linking video output element failed

(python3:27803): GLib-GObject-CRITICAL **: 16:09:02.159: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_object_ref: assertion 'object != NULL' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.159: gst_object_unref: assertion 'object != NULL' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.160: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.160: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.160: gst_bin_remove: assertion 'GST_IS_ELEMENT (element)' failed

(python3:27803): GStreamer-CRITICAL **: 16:09:02.160: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed
Linking video output element failed
Traceback (most recent call last):
  File "gui_main.py", line 233, in <module>
    top         = TopLevel()
  File "gui_main.py", line 52, in __init__
    self.init_ui()
  File "gui_main.py", line 92, in init_ui
    self.online_training_tab    = OnlineTraining(self.data_tools_tab.data_collected)
  File "/home/prover/Work/PythonMyoLinux/gui_demo/online_train.py", line 363, in __init__
    self.init_ui()
  File "/home/prover/Work/PythonMyoLinux/gui_demo/online_train.py", line 567, in init_ui
    self.move_select = self.MovementsSelection(self.movements_selected, self.check_ready_to_start)
  File "/home/prover/Work/PythonMyoLinux/gui_demo/online_train.py", line 80, in __init__
    self.init_ui()
  File "/home/prover/Work/PythonMyoLinux/gui_demo/online_train.py", line 118, in init_ui
    cur_screenshot_path = self.all_screenshot_paths[ord(ex) - ord("A")][1][movement_num - 1]
IndexError: list index out of range
```
Finally, I found this bug is caused by `cur_screenshot_path = self.all_screenshot_paths[ord(ex) - ord("A")][1][movement_num - 1]`. It's pose is "gui_demo/online_train.py/118".
The all_screenshot_paths index out of range. But I don't know why.
